# Generated by Django 5.0.7 on 2024-08-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_city_profile_invite_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
