# Generated by Django 5.0.7 on 2024-08-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_blog_remove_readingprogress_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
