# Generated by Django 5.0.7 on 2024-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_bio_remove_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=353000000000, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
