# Generated by Django 5.0.7 on 2024-08-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_address_orderhistory_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
