# Generated by Django 5.0.7 on 2024-09-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_invite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='invite_code',
        ),
    ]
