# Generated by Django 5.0.7 on 2024-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='isbn',
        ),
        migrations.AddField(
            model_name='catalog',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
